---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cocktails
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      application: frontend
  template:
    metadata:
      labels:
        application: frontend
    spec:
      containers:
        - name: application-container
          image: ghcr.io/menacit/demo_apps/frontend:v1
          ports:
            - name: http-server
              containerPort: 8000
          env:
            - name: APP_RECIPES_URL
              value: http://recipes
            - name: APP_ANALYTICS_URL
              value: http://analytics
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
