---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shared
  name: authentication
spec:
  replicas: 3
  selector:
    matchLabels:
      application: authentication
  template:
    metadata:
      labels:
        application: authentication
    spec:
      containers:
        - name: application-container
          image: ghcr.io/menacit/demo_apps/authentication:v2
          ports:
            - name: http-server
              containerPort: 8000
          env:
            - name: APP_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: authentication
                  key: signing_key
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
