apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cocktails
  name: recipes
spec:
  replicas: 3
  selector:
    matchLabels:
      application: recipes
  template:
    metadata:
      labels:
        application: recipes
    spec:
      containers:
        - name: application-container
          image: ghcr.io/menacit/demo_apps/recipes:v2
          ports:
            - name: http-api
              containerPort: 1338
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
