---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: cocktails
  name: favorites
spec:
  podSelector:
    matchLabels:
      application: favorites
  ingress:
    - from:
        - podSelector:
            matchLabels:
              application: frontend
  egress:
    - to:
        - podSelector:
            matchLabels:
              application: database
