---
apiVersion: v1
kind: Pod
metadata:
  namespace: cocktails
  name: recipes
  labels:
    application: recipes
spec:
  containers:
    - name: application-container
      image: ghcr.io/menacit/demo_apps/recipes:v1
      ports:
        - name: http-api
          containerPort: 1338
      env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
