---
apiVersion: v1
kind: Secret
metadata:
  namespace: cocktails
  name: database
stringData:
  user: example_user
  password: AN_EXAMPLE_PASSWORD
  access_configuration.json: |-
    [
      {
        "username": "example_user",
        "password": "AN_EXAMPLE_PASSWORD",
        "perms": ["all"]
      },
      {"username": "*", "perms": ["status", "ready"]}
    ]
