---
apiVersion: v1
kind: Service                                        
metadata:
  namespace: cocktails
  name: favorites
spec:
  selector:
    application: favorites
  ports:
    - port: 80
      targetPort: http-api
